version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./.prod
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    ports:
      - 3000:3000
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:3500'
    depends_on:
      - frontend